# Compiler and flags
COMPILER ?= gcc
FLAGS ?= -O2 -Wall -Wno-variadic-macros -pedantic -g -pthread -lgnuplot_i -luuid
LDFLAGS ?= -g
LDLIBS = -lm -lgsl -lgslcblas -lpthread -luuid -llapacke -llapack -lblas

# Executable names
TEST_EXECUTABLE = unit_test_runner

# Directories
TEST_DIR = unit_test
SRC_DIR = src
INCLUDE_DIR = include
OBJ_DIR = obj
LIB_DIR = lib

# Source files
TEST_SRCS = $(wildcard $(TEST_DIR)/*.c)
TEST_OBJS = $(patsubst $(TEST_DIR)/%.c,$(OBJ_DIR)/%.o,$(TEST_SRCS))

# Main source files (excluding main.o)
SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRCS))
OBJS_NO_MAIN = $(filter-out $(OBJ_DIR)/main.o, $(OBJS))

# Targets
.PHONY: test clean

test: $(OBJ_DIR) $(TEST_EXECUTABLE)

$(TEST_EXECUTABLE): $(TEST_OBJS) $(LIB_DIR)/unity.o $(OBJS_NO_MAIN)
	$(COMPILER) $(LDFLAGS) -o $@ $^ $(LDLIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	$(COMPILER) $(FLAGS) -I$(INCLUDE_DIR) -I$(LIB_DIR) -o $@ -c $<

$(OBJ_DIR)/%.o: $(TEST_DIR)/%.c
	$(COMPILER) $(FLAGS) -I$(INCLUDE_DIR) -I$(LIB_DIR) -I$(SRC_DIR) -o $@ -c $<

$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(OBJ_DIR)/*.o
	rm -f $(TEST_EXECUTABLE)
